name: Lint, Type Check, Format and Test
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**/*.ts"
      - "**/*.tsx"

jobs:
  next-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: pnpm/action-setup@v2
        with:
          version: 8
          node-version: 20

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run lint
        run: |
          pnpm run lint

      - name: Run type check
        run: |
          pnpm run type-check
          
      - name: Run format check
        run: |
          pnpm run format

  frontend-test:
    name: frontend-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: pnpm/action-setup@v2
        with:
          version: 8
          node-version: 20"

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run test
        run: |
          pnpm run test
